name: Create release from tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      XAPI_VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          pip install build
          sudo apt-get install ocaml dune libfindlib-ocaml-dev libdune-ocaml-dev libcmdliner-ocaml-dev

      - name: Generate python package for XenAPI
        run: |
          ./configure --xapi-version=${{ github.ref_name }}
          make python

      - name: Draft Release ${{ github.ref_name }}
        run: gh release create ${{ github.ref_name }} --draft --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload artifacts
        run: gh release upload ${{ github.ref_name }} scripts/examples/python/dist/* 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
